const employees = [
  {
    id: 1,
    firstName: "Aryan",
    email: "e@e.com",
    password: "123",
    tasks: [
      {
        title: "Fix login bug",
        description: "Resolve the login issue reported by the QA team.",
        date: "2024-01-01",
        category: "Development",
        active: true,
        newTask: false,
        failed: false,
        completed: false,
      },
      {
        title: "Prepare sprint report",
        description: "Generate and submit the sprint progress report.",
        date: "2024-01-03",
        category: "Management",
        active: false,
        newTask: false,
        failed: false,
        completed: true,
      },
      {
        title: "Update documentation",
        description: "Add the latest API changes to the project documentation.",
        date: "2024-01-05",
        category: "Documentation",
        active: true,
        newTask: false,
        failed: false,
        completed: false,
      },
    ],
    taskNumbers: {
      active: 2,
      newTask: 0,
      failed: 0,
      completed: 1,
    },
  },
  {
    id: 2,
    firstName: "Vikram",
    email: "employee2@example.com",
    password: "123",
    tasks: [
      {
        title: "Design mockup for homepage",
        description: "Create an updated design for the homepage using Figma.",
        date: "2024-01-02",
        category: "Design",
        active: true,
        newTask: false,
        failed: false,
        completed: false,
      },
      {
        title: "Fix header responsiveness",
        description: "Ensure the website header works well on all devices.",
        date: "2024-01-04",
        category: "Development",
        active: false,
        newTask: false,
        failed: true,
        completed: false,
      },
      {
        title: "Test checkout flow",
        description: "Perform end-to-end testing of the checkout process.",
        date: "2024-01-06",
        category: "Testing",
        active: true,
        newTask: false,
        failed: false,
        completed: false,
      },
      {
        title: "Conduct team meeting",
        description: "Host a meeting to discuss project timelines.",
        date: "2024-01-07",
        category: "Management",
        active: false,
        newTask: false,
        failed: false,
        completed: true,
      },
      {
        title: "Find Placce for Office Party",
        description:
          "Find a farmhouse or a nice place to counduct our office party.",
        date: "2024-01-07",
        category: "Management",
        active: false,
        newTask: true,
        failed: false,
        completed: false,
      },
      {
        title: "Client meeting",
        description: "Host a meeting to find is prototype satisfactory or not.",
        date: "2024-01-07",
        category: "Management",
        active: false,
        newTask: true,
        failed: false,
        completed: false,
      },
    ],
    taskNumbers: {
      active: 2,
      newTask: 2,
      failed: 1,
      completed: 1,
    },
  },
  {
    id: 3,
    firstName: "Kiran",
    email: "employee3@example.com",
    password: "123",
    tasks: [
      {
        title: "Set up CI/CD pipeline",
        description:
          "Implement continuous integration and deployment for the project.",
        date: "2024-01-03",
        category: "Development",
        active: false,
        newTask: true,
        failed: false,
        completed: false,
      },
      {
        title: "Create marketing campaign",
        description: "Design and schedule posts for the January campaign.",
        date: "2024-01-05",
        category: "Marketing",
        active: false,
        newTask: false,
        failed: false,
        completed: true,
      },
      {
        title: "Test checkout flow",
        description: "Perform end-to-end testing of the checkout process.",
        date: "2024-01-06",
        category: "Testing",
        active: true,
        newTask: false,
        failed: false,
        completed: false,
      },
    ],
    taskNumbers: {
      active: 1,
      newTask: 1,
      failed: 0,
      completed: 1,
    },
  },
  {
    id: 4,
    firstName: "Suresh",
    email: "employee4@example.com",
    password: "123",
    tasks: [
      {
        title: "Optimize database queries",
        description: "Improve the performance of slow database queries.",
        date: "2024-01-02",
        category: "Database",
        active: true,
        newTask: false,
        failed: false,
        completed: false,
      },
      {
        title: "Resolve security vulnerabilities",
        description: "Patch the identified security issues in the app.",
        date: "2024-01-04",
        category: "Security",
        active: false,
        newTask: true,
        failed: false,
        completed: false,
      },
      {
        title: "Testing Flow",
        description: "Perform end-to-end testing of the checkout process.",
        date: "2024-01-06",
        category: "Testing",
        active: true,
        newTask: false,
        failed: false,
        completed: false,
      },
    ],
    taskNumbers: {
      active: 2,
      newTask: 1,
      failed: 0,
      completed: 0,
    },
  },
  {
    id: 5,
    firstName: "Rohan",
    email: "employee5@example.com",
    password: "123",
    tasks: [
      {
        title: "Build analytics dashboard",
        description: "Create a dashboard for visualizing user data.",
        date: "2024-01-01",
        category: "Development",
        active: true,
        newTask: false,
        failed: false,
        completed: false,
      },
      {
        title: "Refactor old code",
        description: "Update the legacy code to follow best practices.",
        date: "2024-01-03",
        category: "Maintenance",
        active: false,
        newTask: false,
        failed: true,
        completed: false,
      },
      {
        title: "Conduct code review",
        description: "Review code submitted by peers and provide feedback.",
        date: "2024-01-05",
        category: "Collaboration",
        active: false,
        newTask: true,
        failed: false,
        completed: false,
      },
    ],
    taskNumbers: {
      active: 1,
      newTask: 1,
      failed: 1,
      completed: 0,
    },
  },
];

const admin = [
  {
    id: 1,
    email: "admin@example.com",
    password: "123",
  },
];

export function setLocalStorage() {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
}

export function getLocalStorage() {
  let employees = JSON.parse(localStorage.getItem("employees"));
  let admin = JSON.parse(localStorage.getItem("admin"));
  return {employees, admin};
}